export const projects = [
  {
    title: 'PixelWhiz',
    description: "This SaaS app utilizes Cloudinary AI which allows users to modify images in a variety of ways. They can remove items from images, manipulate image colours, generate fill and restore old images.",
      image: '/images/Homepage.png',
      tags: ['NextJs', 'TypeScript', 'TailwindCSS', 'Clerk', 'MongoDB', 'ShadCN', 'Stripe'],
    source: 'https://pixelwhiz-aa3t-fuodhwd1y-willfranklands-projects.vercel.app',
    visit: 'https://github.com/will-frankland/saas_project',
    id: 0,
  },
  {
    title: 'CarHub',
    description: "A mock car rental website that utilizes API calls to collect car images and data, this can then be filtered by year or fuel and search functionality for Make and Model also exists.",
      image: '/images/Landing_Section.png',
      tags: ['NextJs', 'TypeScript', 'TailwindCSS', 'HTML', 'CSS'],
    source: 'https://car-showcase-mpmq-4l40y4xlk-will-frankland.vercel.app',
    visit: 'https://github.com/will-frankland/car_showcase',
    id: 1,
  },
  {
    title: 'Shop Admin Dashboard',
    description: "A mock shop admin-dashboard built using React, Tailwind and Syncfusion that displays data such as financials, customers and employees as well as Calendar and Kanban apps and a variety of charts with random data. Also contains theme settings and the ability to turn on dark-mode",
      image: '/images/admin-dashboard.png',
      tags: ['React', 'Tailwind', 'Syncfusion', 'Node.js', 'HTML', 'CSS'],
    source: 'https://syncfucsion-dashboard-site.netlify.app',
    visit: 'https://github.com/will-frankland/admin-dashboard/tree/master/React/admin-dashboard',
    id: 2,
  },
  {
    title: 'Fine Dining Restaurant',
    description: "A single-page website created in React that showcases a fine-dining restaurant complete with a color theme, chef's word, embedded video, a gallery with slider, newsletter subscription, and restaurant details alongside high-quality photos.",
      image: '/images/restaurant-home.png',
      tags: ['React', 'Node.js', 'HTML', 'CSS'],
    source: 'https://fine-dining-app.netlify.app',
    visit: 'https://github.com/will-frankland/restaurant-app',
    id: 3,
  },
  {
    title: 'WF Media (YouTube Clone)',
    description: "A YouTube clone app build using React, Node, Axios, and MaterialUI. Users can browse new videos, search and see recommended videos, access channels with dedicated Channel Cards, control videos as well as see likes and views",
      image: '/images/WF-media.png',
      tags: ['React', 'Node.js', 'Axios', 'MUI', 'HTML', 'CSS'],
    source: 'https://wfmedia-ytclone.netlify.app',
    visit: 'https://github.com/will-frankland/youtube_clone',
    id: 4,
  },
  {
    title: 'Thera-Match',
    description:"A React app built as part of my final group project which enables users to find and match with potential therapists based upon their criteria. Utilizes the 'tinder-swipe' mechanism when searching for therapists and then allows for instant chat, video calls, SMS notifications for therapists, a calendar to show appointments and contains a blog page",
    image: '/images/Thera-Match.png',
    tags: ['React', 'Express', 'Node.js', 'SQL', 'HTML', 'CSS'],
    source: '',
    visit: 'https://github.com/will-frankland/Thera-match',
    id: 5,
  },
  {
    title: 'GPT-3 Clone',
    description: "A single-page React app created to clone GPT-3 and practice React alongside heavy CSS styling. The site utilizes an array of slick styles and components and is fully mobile responsive. Users can click the tabs in the header and the site will auto-scroll to the specified section",
      image: '/images/gpt3clone.png',
      tags: ['React', 'HTML', 'CSS'],
    source: 'https://openaiclone.netlify.app',
    visit: 'https://github.com/will-frankland/gpt3-wf',
    id: 6,
  },
  {
    title: 'Expense Tracker',
    description: "A simple expense tracker built in React where users can add, remove and edit expenses",
      image: '/images/expense-tracker.png',
      tags: ['React', 'HTML', 'CSS'],
    source: '',
    visit: 'https://github.com/will-frankland/expense-tracker-react',
    id: 7,
  },
  {
    title: 'Weather API App',
    description: "A simple weather app built with vanilla JavaScript which requests users location and then display the weather in their location. Temperature can be clicked to cycle from Celsius to Fahrenheit",
    image: '/images/weather-app.png',
    tags: ['JavaScript', 'HTML', 'CSS'],
    source: '',
    visit: 'https://github.com/will-frankland/weather-app-js',
    id: 8,
  },
  {
    title: 'React Calculator',
    description: "A single page React app calcualtor built to practice fundamentals",
    image: '/images/calculator-react.png',
    tags: ['JavaScript', 'React', 'HTML', 'CSS'],
    source: '',
    visit: 'https://github.com/will-frankland/calculator-react',
    id: 9,
  },
];

export const TimeLineData = [
  { year: 2015, text: 'Graduated college in the UK with a Mechanical Engineering Diploma and began work as a Process Engineer', },
  { year: 2018, text: 'Took a contracting role utilizing CAD for Royal Navy Submarines', },
  { year: 2019, text: 'Moved to Toronto, Canada, began work as a Field Service Technician', },
  { year: 2022, text: 'Completed Web Development Bootcamp with Lighthouse Labs in Toronto', },
  { year: 2023, text: 'First Web Developer job!', },
];