export const projects = [
  {
    title: 'Shop Admin Dashboard',
    description: "A mock shop admin-dashboard built using React, Tailwind and Syncfusion that displays data such as financials, customers and employees as well as Calendar and Kanban apps and a variety of charts with random data. Also contains theme settings and the ability to turn on dark-mode.",
      image: '/images/admin-dashboard.png',
      tags: ['React', 'Tailwind', 'Syncfusion', 'Node.js', 'HTML', 'CSS'],
    source: 'https://syncfucsion-dashboard-site.netlify.app',
    visit: 'https://github.com/will-frankland/admin-dashboard/tree/master/React/admin-dashboard',
    id: 0,
  },
  {
    title: 'Thera-Match',
    description:"A React app built to enable users to find and match with potential therapists based upon their criteria. Utilizes the 'tinder-swipe' mechanism when searching for therapists and then allows for instant chat, video calls, SMS notifications for therapists, a calendar to show appointments and contains a blog page.",
    image: '/images/Thera-Match.png',
    tags: ['React', 'Express', 'Node.js', 'SQL', 'HTML', 'CSS'],
    source: '',
    visit: 'https://github.com/will-frankland/Thera-match',
    id: 1,
  },
  {
    title: 'Expense Tracker',
    description: "A simple expense tracker built in React where users can add, remove and edit expenses.",
      image: '/images/expense-tracker.png',
      tags: ['React', 'HTML', 'CSS'],
    source: '',
    visit: 'https://github.com/will-frankland/expense-tracker-react',
    id: 2,
  },
  {
    title: 'Weather API App',
    description: "A simple weather app built with vanilla JavaScript which requests users location and then display the weather in their location. Temperature can be clicked to cycle from Celsius to Fahrenheit",
    image: '/images/weather-app.png',
    tags: ['JavaScript', 'HTML', 'CSS'],
    source: '',
    visit: 'https://github.com/will-frankland/weather-app-js',
    id: 3,
  },
  {
    title: 'React Calculator',
    description: "A single page React app calcualtor built to practice fundamentals",
    image: '/images/calculator-react.png',
    tags: ['JavaScript', 'React', 'HTML', 'CSS'],
    source: '',
    visit: 'https://github.com/will-frankland/calculator-react',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2015, text: 'Graduated college in the UK with a Mechanical Engineering Diploma and began work as a Process Engineer', },
  { year: 2018, text: 'Took a contracting role utilizing CAD for Royal Navy Submarines', },
  { year: 2019, text: 'Moved to Toronto, Canada, began work as a Field Service Technician', },
  { year: 2022, text: 'Completed Web Development Bootcamp with Lighthouse Labs in Toronto', },
  { year: 2023, text: 'Working on building my web portfolio', },
];